language: java
dist: trusty

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "esg-apps-team"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=esg-apps-team -Dsonar.projectKey=esg-apps-team_esgcoin -Dsonar.login=$SONAR_KEY -Dsonar.verbose=true -Dsonar.exclusions=src/brs/grpc/proto/BrsApi.java,src/brs/grpc/proto/BrsApiServiceGrpc.java,src/brs/schema/**

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
